import type { ActionFunctionArgs, LoaderFunctionArgs } from "react-router";
import { authenticate } from "../shopify.server";

type GenerateRequest = {
  title?: unknown;
  imageUrl?: unknown;
};

const jsonResponse = (body: unknown, init?: ResponseInit) => {
  return new Response(JSON.stringify(body), {
    ...init,
    headers: {
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });
};

const coerceString = (value: unknown) => {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length ? trimmed : null;
};

export const loader = async ({ request }: LoaderFunctionArgs) => {
  await authenticate.admin(request);
  return jsonResponse(
    { ok: false, error: "Method not allowed" },
    { status: 405 },
  );
};

export const action = async ({ request }: ActionFunctionArgs) => {
  await authenticate.admin(request);

  const contentType = request.headers.get("content-type") ?? "";
  if (!contentType.toLowerCase().includes("application/json")) {
    return jsonResponse(
      { ok: false, error: "Expected application/json" },
      { status: 415 },
    );
  }

  let payload: GenerateRequest;
  try {
    payload = (await request.json()) as GenerateRequest;
  } catch {
    return jsonResponse({ ok: false, error: "Invalid JSON" }, { status: 400 });
  }

  const title = coerceString(payload.title) ?? "Untitled product";
  const imageUrl = coerceString(payload.imageUrl);

  const listing = {
    title,
    descriptionHtml: `<p>${title}</p><p>Generated by ListingMuse (mock).</p>`,
    bulletPoints: [
      "Mock output for phase-1 scaffolding",
      "Replace with real model + prompt pipeline",
      "Apply via /app/api/apply",
    ],
    tags: ["listingmuse", "generated"],
    seo: {
      title,
      description: `Generated listing for ${title}`,
    },
    images: imageUrl ? [imageUrl] : [],
  };

  return jsonResponse({ ok: true, generationId: `gen_${Date.now()}`, listing });
};
